export const dailyClassQuests = {
  ghostrunner: [
    'Hoàn thành nhiệm vụ dưới 2 phút',
    'Hoàn tất 3 nhiệm vụ ngắn (≤ 10 ký tự)',
    'Tránh xao nhãng trong 30 phút',
    'Làm việc nhà kiểu “speedrun” trong 15 phút',
    'Tắt thông báo 1 giờ liền',
    'Sắp xếp gọn lại không gian làm việc',
    'Xử lý gọn lẹ một nhiệm vụ đơn giản',
    'Đóng tất cả tab & app không dùng',
  ],
  netcrasher: [
    'Gỡ lỗi hoặc sửa chữa thứ gì đó',
    'Học hoặc viết code 30 phút trở lên',
    'Hoàn thành một nhiệm vụ liên quan đến công nghệ',
    'Ghi chú lại một điều bạn đã học',
    'Dọn dẹp thư mục hoặc cấu trúc file',
    'Tự động hóa hoặc tối ưu hóa việc lặp lại',
    'Refactor code hoặc văn bản cũ cho rõ ràng',
    'Đọc một bài viết về xu hướng công nghệ',
  ],
  synthmancer: [
    'Duy trì chuỗi streak của bạn',
    'Hoàn thành 5 nhiệm vụ trong ngày',
    'Giữ vững thói quen 3 ngày liên tiếp',
    'Xem lại tiến trình tuần này của bạn',
    'Làm một việc giúp nâng cao kỹ năng lâu dài',
    'Nghỉ ngơi 10 phút để tĩnh tâm',
    'Cân bằng làm & nghỉ bằng Pomodoro (3 vòng)',
    'Suy ngẫm về một khía cạnh bản thân cần cải thiện',
  ],
};
