export const dailyClassQuests = {
  ghostrunner: [
    'Complete a task in under 2 minutes',
    'Finish 3 small tasks (≤ 10 chars)',
    'Avoid distractions for 30 min',
    'Do a 15-minute speedrun of chores',
    'Silence notifications for 1 hour',
    'Organize your workspace swiftly',
    'Knock out a low-effort task instantly',
    'Close all unused tabs & apps',
  ],
  netcrasher: [
    'Debug or fix something',
    'Study or write code for 30+ minutes',
    'Complete a tech-related task',
    'Document one learning in a note',
    'Tidy up files or folder structures',
    'Automate or optimize a repetitive task',
    'Refactor old code or text for clarity',
    'Read an article on tech trends',
  ],
  synthmancer: [
    'Maintain your streak',
    'Complete 5 tasks today',
    'Stay consistent for 3 days in a row',
    'Review your progress this week',
    'Do a task that builds long-term skill',
    'Take a 10-minute mindfulness break',
    'Balance work & rest with Pomodoro (3 rounds)',
    'Reflect on one personal improvement area',
  ],
};
