export const initialSimPlayers = [
  {
    id: 'p1',
    name: 'Bảo Vệ Số',
    playerClass: 'ghostrunner',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
  {
    id: 'p2',
    name: 'Dũng Sĩ Pixel',
    playerClass: 'netcrasher',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
  {
    id: 'p3',
    name: 'Thầy Pháp Synth',
    playerClass: 'synthmancer',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
  {
    id: 'p4',
    name: 'Nữ Chúa Glitch',
    playerClass: 'ghostrunner',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
  {
    id: 'p5',
    name: 'ZeroDay Hacker',
    playerClass: 'netcrasher',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
  {
    id: 'p6',
    name: 'Kỵ Sĩ Byte',
    playerClass: 'synthmancer',
    xp: 0,
    tasksCompleted: 0,
    bossesDefeated: 0,
  },
];
